apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-user-deployment
  labels:
    app: service-user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-user
  template:
    metadata:
      labels:
        app: service-user
    spec:
      containers:
      - name: service-user
        image: registry.cn-hangzhou.aliyuncs.com/sunnanjun/mycloud
        ports:
        - containerPort: 8899