apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-user-deployment
  labels:
    app: service-user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-user
  template:
    metadata:
      labels:
        app: service-user
    spec:
      containers:
      - name: service-user
        image: registry.cn-hangzhou.aliyuncs.com/sunnanjun/mycloud:latest
        ports:
        - containerPort: 8899
      imagePullSecrets:
            - name: registrykey-01

---
apiVersion: v1
kind: Service
metadata:
  name: service-user-service
spec:
  type: NodePort
  ports:
  - port: 8899
    targetPort: 8899
    protocol: TCP
    nodePort: 32222
  selector:
    app: service-user
