apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-{{project_name}}-{{app_name}}
  labels:
    app: deployment-{{project_name}}-{{app_name}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{project_name}}-{{app_name}}
  template:
    metadata:
      labels:
        app: {{project_name}}-{{app_name}}
    spec:
      containers:
      - name: {{project_name}}-{{app_name}}
        image: registry.cn-beijing.aliyuncs.com/tangyuan/{{project_name}}-{{app_name}}:latest
        ports:
        - containerPort: {{app_port}}
        env:
        - name: MYSQL_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: username
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        - name: APP_PORT
          value: '{{app_port}}'
      imagePullSecrets:
            - name: registrykey-01

---
apiVersion: v1
kind: Service
metadata:
  name: service-{{project_name}}-{{app_name}}
spec:
  type: NodePort
  ports:
  - port: {{app_port}}
    targetPort: {{app_port}}
    protocol: TCP
  selector:
    app: {{project_name}}-{{app_name}}
