apiVersion: v1
kind: Service
metadata:
  name: service-{{project_name}}-{{app_name}}
spec:
  type: NodePort
  ports:
  - port: {{app_port}}
    targetPort: {{app_port}}
    protocol: TCP
  selector:
    app: {{project_name}}-{{app_name}}
